# From: https://github.com/CircleCI-Public/android-testing-circleci-examples/blob/main/.circleci/config.yml
version: 2.1

orbs:
  android: circleci/android@2.1.2
  gcp-cli: circleci/gcp-cli@2.2.0

jobs:
  unit-test:
    executor:
      name: android/android-machine
      tag: 2022.07.1 # pick image tag from https://circleci.com/developer/images/image/cimg/android#image-tags
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  android-test:
    parameters:
      system-image:
        type: string
        default: system-images;android-30;google_apis;x86
    executor:
      name: android/android-machine
      tag: 2022.07.1 # pick image tag from https://circleci.com/developer/images/image/cimg/android#image-tags
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: << parameters.system-image >>
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  test-and-build:
    jobs:
      - unit-test:
          filters: # Execute for all tags, and for commits to branches.
            tags: # Re-adds tags, which are ignored by default.
              only: /.*/
      - android-test:
          matrix:
            alias: android-test-all
            parameters:
              system-image:
                - system-images;android-30;google_apis;x86
                - system-images;android-29;google_apis;x86
          name: android-test-<<matrix.system-image>>
          requires:
            - unit-test
          filters: # Only execute for tags, ignore commits to branches.
            tags:
              only: /^.*/
            branches:
              only: master